name: Build Chat++
on: [push]
jobs:
  build-chatpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS.
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install NPM modules.  
        run: npm ci
      - name: Run Makefile.
        run: make
